### PR TITLE
Fix feedback when deleting containers

### LINKED ISSUE #144: No feedback while deleting containers and delete requests gets 404 response
I was trying to delete containers and it was really a bad experience deleting them. There wasn't any page reload and feedback, all I had to do was to reload page manually in order to see that containers were deleted or not.

### PR DESCRIPTION
**Pull request by nt1m**
Fixes #144

### CODE REVIEW

**Comment by nt1m** [comment]
Fixes #144.

Containers that failed to create now are recycled instead of having a "Start failed" status, because the API now handles errors, and will instead return 500 if the container isn't created. Also, the API that deletes containers needs a container ID, and a container that failed to be created doesn't have one.

**Comment by bnjbvr** [comment]
Sorry I am not confident reviewing the JSON-patch and frontend changes, deferring to Jan.

File: lib/machines.js [hunk 1]
```diff
@@ -205,7 +205,9 @@ exports.spawn = function (user, projectId, callback) {
   docker.runContainer({ host, image, ports }, (error, container, logs) => {
     if (error) {
       log('spawn', image, error);
-      machine.status = 'start-failed';
+      // Recycle the machine if it failed to spawn, error feedback is handled by the API 
+      machine.status = 'new';
+      machine.docker.container = '';
```
Comment (jankeromnes) [inline lib/machines.js]: You don't need to recycle the machine here, because its `status` is already `'new'` (guaranteed by the above call to `getOrCreateNewMachine()`) and its `machine.docker.container` should already be empty.

Instead, I think you can simply remove the `machine.status = 'start-failed'` (as you did) and also the `db.save()`.

File: static/js/janitor.js [hunk 2]
```diff
@@ -178,12 +178,13 @@ function updateFormStatus (form, status, message) {
...
       break;
     default:
-      Array.forEach(form.elements, function (element) {
-        element.classList.remove('disabled');
-      });
       break;
   }
 
+  Array.forEach(form.elements, function (element) {
+    element.classList.remove('disabled');
```
Comment (jankeromnes) [inline static/js/janitor.js]: Why are you changing the logic here? The previous code purposefully didn't remove the `disabled` class on buttons if the status was a `success` or an `error` (forcing you to modify any field's value before being able to submit again, because submitting the exact same input doesn't make sense if you just had an error or a success).

**Comment by jankeromnes** [comment]
Addressed my own nits.
